-- RBAC 
USE ROLE SECURITYADMIN;
-- Create Role for Developers
CREATE ROLE ROLE_DATA_ENG;

-- Create Role for Lead Developers
CREATE ROLE ROLE_DATA_LEAD;

-- Create Role for CI/CD Automation
CREATE ROLE ROLE_CI_CD;

-- Developer User
CREATE USER DEVELOPER_USER PASSWORD='password' DEFAULT_ROLE=ROLE_DATA_ENG MUST_CHANGE_PASSWORD=TRUE ; -- We can specify email for each

-- Lead Developer User
CREATE USER LEAD_USER PASSWORD='password' DEFAULT_ROLE=ROLE_DATA_LEAD MUST_CHANGE_PASSWORD=TRUE ; 

-- CI/CD Service Account
CREATE USER CI_CD_USER PASSWORD='secure_password' DEFAULT_ROLE=ROLE_CI_CD MUST_CHANGE_PASSWORD=TRUE ;


-- Grant Developer Role to Developer User
GRANT ROLE ROLE_DATA_ENG TO USER DEVELOPER_USER;

-- Grant Lead Role to Lead User
GRANT ROLE ROLE_DATA_LEAD TO USER LEAD_USER;

-- Grant CI/CD Role to Service Account
GRANT ROLE ROLE_CI_CD TO USER CI_CD_USER;


-- Create Databases for DEV, PRE-PROD, and PROD environments
USE ROLE SYSADMIN;
CREATE DATABASE DEV_DB;
CREATE DATABASE PRE_PROD_DB;
CREATE DATABASE PROD_DB;


-- Create Dedicated Warehouses for each environment
CREATE WAREHOUSE DEV_WH WITH WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 300 AUTO_RESUME = TRUE;
CREATE WAREHOUSE PRE_PROD_WH WITH WAREHOUSE_SIZE = 'SMALL' AUTO_SUSPEND = 300 AUTO_RESUME = TRUE;
CREATE WAREHOUSE PROD_WH WITH WAREHOUSE_SIZE = 'MEDIUM' AUTO_SUSPEND = 300 AUTO_RESUME = TRUE;
-- Grant access to DEV environment for developers
GRANT USAGE ON WAREHOUSE DEV_WH TO ROLE ROLE_DATA_ENG;
GRANT ALL PRIVILEGES ON DATABASE DEV_DB TO ROLE ROLE_DATA_ENG;


-- Grant access to PRE-PROD environment for leads
GRANT USAGE ON WAREHOUSE PRE_PROD_WH TO ROLE ROLE_DATA_LEAD;
GRANT ALL PRIVILEGES ON DATABASE PRE_PROD_DB TO ROLE ROLE_DATA_LEAD;

-- Grant access to PROD environment for CI/CD automation
GRANT USAGE ON WAREHOUSE PROD_WH TO ROLE ROLE_CI_CD;
GRANT ALL PRIVILEGES ON DATABASE PROD_DB TO ROLE ROLE_CI_CD;



