name: dbt CI/CD Pipeline

on:
  push:
    branches:
      - develop
      - pre_prod
      - prod
  pull_request:
    branches:
      - pre_prod
      - prod

jobs:
  # Step 1: Slim CI: Running only modified dbt models
  slim-ci:
    name: dbt Slim CI - Run Modified Models
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dbt
        run: |
          pip install dbt-snowflake

      - name: Generate Manifest for Main Branch
        if: github.ref == 'refs/heads/main'
        run: |
          dbt compile --target-path=prod-run-artifacts

      - name: Generate Manifest for Feature Branch
        if: github.ref != 'refs/heads/main'
        run: |
          dbt compile  # Generate manifest for the feature branch

      - name: List Modified Models (Slim CI)
        run: |
          MODIFIED_MODELS=$(dbt ls --select state:modified+ --defer --state=prod-run-artifacts)
          echo "Modified Models: $MODIFIED_MODELS"
          echo "::set-output name=modified_models::$MODIFIED_MODELS"

      - name: Run Modified dbt Models
        run: |
          if [[ -n "$MODIFIED_MODELS" ]]; then
            dbt run --select state:modified+ --defer --state=prod-run-artifacts  # Run only modified models
          else
            echo "No modified models found, skipping dbt run."
          fi

  # Step 2: Deploy to Pre-Production DB
  deploy-preprod:
    name: Deploy to Pre-Production
    runs-on: ubuntu-latest
    needs: slim-ci
    if: github.ref == 'refs/heads/pre_prod'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dbt
        run: |
          pip install dbt-snowflake

      - name: Deploy to Pre-Production DB
        run: |
          dbt run --target pre_prod

  # Step 3: Deploy to Production DB
  deploy-prod:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: deploy-preprod
    if: github.ref == 'refs/heads/prod'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dbt
        run: |
          pip install dbt-snowflake

      - name: Deploy to Production DB
        run: |
          dbt run --target prod